/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTenantTablesRouteImport } from './routes/_authenticated/tenant-tables'
import { Route as AuthenticatedMigrationsIndexRouteImport } from './routes/_authenticated/migrations/index'
import { Route as AuthenticatedMigrationRunsIndexRouteImport } from './routes/_authenticated/migration-runs/index'
import { Route as AuthenticatedEnvironmentsIndexRouteImport } from './routes/_authenticated/environments/index'
import { Route as AuthenticatedEnvironmentsNewRouteImport } from './routes/_authenticated/environments/new'
import { Route as AuthenticatedEnvironmentsIdEditRouteImport } from './routes/_authenticated/environments/$id/edit'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenantTablesRoute =
  AuthenticatedTenantTablesRouteImport.update({
    id: '/tenant-tables',
    path: '/tenant-tables',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMigrationsIndexRoute =
  AuthenticatedMigrationsIndexRouteImport.update({
    id: '/migrations/',
    path: '/migrations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMigrationRunsIndexRoute =
  AuthenticatedMigrationRunsIndexRouteImport.update({
    id: '/migration-runs/',
    path: '/migration-runs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnvironmentsIndexRoute =
  AuthenticatedEnvironmentsIndexRouteImport.update({
    id: '/environments/',
    path: '/environments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnvironmentsNewRoute =
  AuthenticatedEnvironmentsNewRouteImport.update({
    id: '/environments/new',
    path: '/environments/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnvironmentsIdEditRoute =
  AuthenticatedEnvironmentsIdEditRouteImport.update({
    id: '/environments/$id/edit',
    path: '/environments/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/tenant-tables': typeof AuthenticatedTenantTablesRoute
  '/environments/new': typeof AuthenticatedEnvironmentsNewRoute
  '/environments/': typeof AuthenticatedEnvironmentsIndexRoute
  '/migration-runs/': typeof AuthenticatedMigrationRunsIndexRoute
  '/migrations/': typeof AuthenticatedMigrationsIndexRoute
  '/environments/$id/edit': typeof AuthenticatedEnvironmentsIdEditRoute
}
export interface FileRoutesByTo {
  '/tenant-tables': typeof AuthenticatedTenantTablesRoute
  '/': typeof AuthenticatedIndexRoute
  '/environments/new': typeof AuthenticatedEnvironmentsNewRoute
  '/environments': typeof AuthenticatedEnvironmentsIndexRoute
  '/migration-runs': typeof AuthenticatedMigrationRunsIndexRoute
  '/migrations': typeof AuthenticatedMigrationsIndexRoute
  '/environments/$id/edit': typeof AuthenticatedEnvironmentsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/tenant-tables': typeof AuthenticatedTenantTablesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/environments/new': typeof AuthenticatedEnvironmentsNewRoute
  '/_authenticated/environments/': typeof AuthenticatedEnvironmentsIndexRoute
  '/_authenticated/migration-runs/': typeof AuthenticatedMigrationRunsIndexRoute
  '/_authenticated/migrations/': typeof AuthenticatedMigrationsIndexRoute
  '/_authenticated/environments/$id/edit': typeof AuthenticatedEnvironmentsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tenant-tables'
    | '/environments/new'
    | '/environments/'
    | '/migration-runs/'
    | '/migrations/'
    | '/environments/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/tenant-tables'
    | '/'
    | '/environments/new'
    | '/environments'
    | '/migration-runs'
    | '/migrations'
    | '/environments/$id/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/tenant-tables'
    | '/_authenticated/'
    | '/_authenticated/environments/new'
    | '/_authenticated/environments/'
    | '/_authenticated/migration-runs/'
    | '/_authenticated/migrations/'
    | '/_authenticated/environments/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenant-tables': {
      id: '/_authenticated/tenant-tables'
      path: '/tenant-tables'
      fullPath: '/tenant-tables'
      preLoaderRoute: typeof AuthenticatedTenantTablesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/migrations/': {
      id: '/_authenticated/migrations/'
      path: '/migrations'
      fullPath: '/migrations/'
      preLoaderRoute: typeof AuthenticatedMigrationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/migration-runs/': {
      id: '/_authenticated/migration-runs/'
      path: '/migration-runs'
      fullPath: '/migration-runs/'
      preLoaderRoute: typeof AuthenticatedMigrationRunsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/environments/': {
      id: '/_authenticated/environments/'
      path: '/environments'
      fullPath: '/environments/'
      preLoaderRoute: typeof AuthenticatedEnvironmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/environments/new': {
      id: '/_authenticated/environments/new'
      path: '/environments/new'
      fullPath: '/environments/new'
      preLoaderRoute: typeof AuthenticatedEnvironmentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/environments/$id/edit': {
      id: '/_authenticated/environments/$id/edit'
      path: '/environments/$id/edit'
      fullPath: '/environments/$id/edit'
      preLoaderRoute: typeof AuthenticatedEnvironmentsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedTenantTablesRoute: typeof AuthenticatedTenantTablesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEnvironmentsNewRoute: typeof AuthenticatedEnvironmentsNewRoute
  AuthenticatedEnvironmentsIndexRoute: typeof AuthenticatedEnvironmentsIndexRoute
  AuthenticatedMigrationRunsIndexRoute: typeof AuthenticatedMigrationRunsIndexRoute
  AuthenticatedMigrationsIndexRoute: typeof AuthenticatedMigrationsIndexRoute
  AuthenticatedEnvironmentsIdEditRoute: typeof AuthenticatedEnvironmentsIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedTenantTablesRoute: AuthenticatedTenantTablesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEnvironmentsNewRoute: AuthenticatedEnvironmentsNewRoute,
  AuthenticatedEnvironmentsIndexRoute: AuthenticatedEnvironmentsIndexRoute,
  AuthenticatedMigrationRunsIndexRoute: AuthenticatedMigrationRunsIndexRoute,
  AuthenticatedMigrationsIndexRoute: AuthenticatedMigrationsIndexRoute,
  AuthenticatedEnvironmentsIdEditRoute: AuthenticatedEnvironmentsIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
